name: CI-CD1

on:
  push:
    branches:
      - master
      
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP_1 }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/HH99FinalProject_BE
            # git config --global --add safe.directory /home/ubuntu/HH99FinalProject_BE
            sudo git pull
            # sudo npm update
            sudo npm install
            sudo pm2 reload all
